<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'site_name',
                'group' => 'general',
                'value_vi' => 'Happy Island Tour',
                'value_en' => 'Happy Island Tour',
                'type' => 'string',
            ],
            [
                'key' => 'site_tagline',
                'group' => 'general',
                'value_vi' => 'Nơi nghỉ dưỡng lý tưởng giữa thiên nhiên',
                'value_en' => 'The perfect retreat in the heart of nature',
                'type' => 'string',
            ],
            [
                'key' => 'logo_url',
                'group' => 'general',
                'value_vi' => '/images/logo.png',
                'value_en' => '/images/logo.png',
                'type' => 'string',
            ],
            [
                'key' => 'favicon_url',
                'group' => 'general',
                'value_vi' => '/favicon.ico',
                'value_en' => '/favicon.ico',
                'type' => 'string',
            ],
            [
                'key' => 'default_check_in_time',
                'group' => 'general',
                'value_vi' => '14:00',
                'value_en' => '14:00',
                'type' => 'string',
            ],
            [
                'key' => 'default_check_out_time',
                'group' => 'general',
                'value_vi' => '12:00',
                'value_en' => '12:00',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_phone_enabled',
                'group' => 'contact',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'contact_action_phone_label',
                'group' => 'contact',
                'value_vi' => 'Gọi điện',
                'value_en' => 'Call',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_phone_icon',
                'group' => 'contact',
                'value_vi' => 'https://img.icons8.com/fluency/96/phone.png',
                'value_en' => 'https://img.icons8.com/fluency/96/phone.png',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_hotline_enabled',
                'group' => 'contact',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'contact_action_hotline_label',
                'group' => 'contact',
                'value_vi' => 'Hotline',
                'value_en' => 'Hotline',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_hotline_icon',
                'group' => 'contact',
                'value_vi' => 'https://img.icons8.com/fluency/96/phone-disconnected.png',
                'value_en' => 'https://img.icons8.com/fluency/96/phone-disconnected.png',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_zalo_enabled',
                'group' => 'contact',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'contact_action_zalo_label',
                'group' => 'contact',
                'value_vi' => 'Zalo',
                'value_en' => 'Zalo',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_zalo_icon',
                'group' => 'contact',
                'value_vi' => 'https://img.icons8.com/fluency/96/zalo.png',
                'value_en' => 'https://img.icons8.com/fluency/96/zalo.png',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_whatsapp_enabled',
                'group' => 'contact',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'contact_action_whatsapp_label',
                'group' => 'contact',
                'value_vi' => 'WhatsApp',
                'value_en' => 'WhatsApp',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_whatsapp_icon',
                'group' => 'contact',
                'value_vi' => 'https://img.icons8.com/fluency/96/whatsapp.png',
                'value_en' => 'https://img.icons8.com/fluency/96/whatsapp.png',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_messenger_enabled',
                'group' => 'contact',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'contact_action_messenger_label',
                'group' => 'contact',
                'value_vi' => 'Messenger',
                'value_en' => 'Messenger',
                'type' => 'string',
            ],
            [
                'key' => 'contact_action_messenger_icon',
                'group' => 'contact',
                'value_vi' => 'https://img.icons8.com/fluency/96/facebook-messenger.png',
                'value_en' => 'https://img.icons8.com/fluency/96/facebook-messenger.png',
                'type' => 'string',
            ],
            [
                'key' => 'enable_bilingual',
                'group' => 'general',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'default_language',
                'group' => 'general',
                'value_vi' => 'vi',
                'value_en' => 'vi',
                'type' => 'string',
            ],
            [
                'key' => 'available_languages',
                'group' => 'general',
                'value_vi' => '["vi","en"]',
                'value_en' => '["vi","en"]',
                'type' => 'json',
            ],

            // SEO Settings
            [
                'key' => 'meta_title',
                'group' => 'seo',
                'value_vi' => 'Happy Island Tour - Đặt phòng Happy Island Tour trực tuyến',
                'value_en' => 'Happy Island Tour - Book your perfect Happy Island Tour online',
                'type' => 'string',
            ],
            [
                'key' => 'meta_description',
                'group' => 'seo',
                'value_vi' => 'Khám phá và đặt phòng Happy Island Tour đẹp nhất với giá tốt nhất. Trải nghiệm nghỉ dưỡng tuyệt vời giữa thiên nhiên.',
                'value_en' => 'Discover and book the most beautiful Happy Island Tours at the best prices. Experience a wonderful retreat in nature.',
                'type' => 'string',
            ],
            [
                'key' => 'meta_keywords',
                'group' => 'seo',
                'value_vi' => 'happy island tour, đặt phòng, nghỉ dưỡng, du lịch, thiên nhiên',
                'value_en' => 'happy island tour, booking, retreat, travel, nature',
                'type' => 'string',
            ],
            [
                'key' => 'og_image',
                'group' => 'seo',
                'value_vi' => '/images/og-image.jpg',
                'value_en' => '/images/og-image.jpg',
                'type' => 'string',
            ],
            [
                'key' => 'google_analytics_id',
                'group' => 'seo',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],

            // Contact Settings
            [
                'key' => 'contact_email',
                'group' => 'contact',
                'value_vi' => 'contact@homestay.com',
                'value_en' => 'contact@homestay.com',
                'type' => 'string',
            ],
            [
                'key' => 'contact_phone',
                'group' => 'contact',
                'value_vi' => '+84 123 456 789',
                'value_en' => '+84 123 456 789',
                'type' => 'string',
            ],
            [
                'key' => 'contact_hotline',
                'group' => 'contact',
                'value_vi' => '1900 1234',
                'value_en' => '1900 1234',
                'type' => 'string',
            ],
            [
                'key' => 'contact_zalo',
                'group' => 'contact',
                'value_vi' => '0123456789',
                'value_en' => '0123456789',
                'type' => 'string',
            ],
            [
                'key' => 'contact_whatsapp',
                'group' => 'contact',
                'value_vi' => '84123456789',
                'value_en' => '84123456789',
                'type' => 'string',
            ],
            [
                'key' => 'contact_address',
                'group' => 'contact',
                'value_vi' => '123 Đường Hoa Mai, Quận 1, TP. Hồ Chí Minh',
                'value_en' => '123 Hoa Mai Street, District 1, Ho Chi Minh City',
                'type' => 'string',
            ],
            [
                'key' => 'google_maps_url',
                'group' => 'contact',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],

            // Social Settings
            [
                'key' => 'social_facebook',
                'group' => 'social',
                'value_vi' => 'https://facebook.com/homestaybooking',
                'value_en' => 'https://facebook.com/homestaybooking',
                'type' => 'string',
            ],
            [
                'key' => 'social_instagram',
                'group' => 'social',
                'value_vi' => 'https://instagram.com/homestaybooking',
                'value_en' => 'https://instagram.com/homestaybooking',
                'type' => 'string',
            ],
            [
                'key' => 'social_youtube',
                'group' => 'social',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],
            [
                'key' => 'social_tiktok',
                'group' => 'social',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],
            [
                'key' => 'social_messenger',
                'group' => 'social',
                'value_vi' => 'https://m.me/homestaybooking',
                'value_en' => 'https://m.me/homestaybooking',
                'type' => 'string',
            ],
            [
                'key' => 'social_zalo',
                'group' => 'social',
                'value_vi' => 'https://zalo.me/0123456789',
                'value_en' => 'https://zalo.me/0123456789',
                'type' => 'string',
            ],

            // Banner 1 Settings
            [
                'key' => 'banner1_enabled',
                'group' => 'banners',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'banner1_variant',
                'group' => 'banners',
                'value_vi' => 'default',
                'value_en' => 'default',
                'type' => 'string',
            ],
            [
                'key' => 'banner1_title',
                'group' => 'banners',
                'value_vi' => 'Ưu đãi mùa hè',
                'value_en' => 'Summer Special',
                'type' => 'string',
            ],
            [
                'key' => 'banner1_subtitle',
                'group' => 'banners',
                'value_vi' => 'Giảm đến 30% cho đặt phòng sớm. Đặt ngay hôm nay!',
                'value_en' => 'Up to 30% off for early bookings. Book today!',
                'type' => 'string',
            ],
            [
                'key' => 'banner1_cta',
                'group' => 'banners',
                'value_vi' => 'Đặt ngay',
                'value_en' => 'Book Now',
                'type' => 'string',
            ],
            [
                'key' => 'banner1_link',
                'group' => 'banners',
                'value_vi' => '/rooms',
                'value_en' => '/rooms',
                'type' => 'string',
            ],
            [
                'key' => 'banner1_image',
                'group' => 'banners',
                'value_vi' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200',
                'value_en' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200',
                'type' => 'string',
            ],

            // Banner 2 Settings
            [
                'key' => 'banner2_enabled',
                'group' => 'banners',
                'value_vi' => 'true',
                'value_en' => 'true',
                'type' => 'boolean',
            ],
            [
                'key' => 'banner2_variant',
                'group' => 'banners',
                'value_vi' => 'gradient',
                'value_en' => 'gradient',
                'type' => 'string',
            ],
            [
                'key' => 'banner2_title',
                'group' => 'banners',
                'value_vi' => 'Khám phá Tour độc đáo',
                'value_en' => 'Discover Unique Tours',
                'type' => 'string',
            ],
            [
                'key' => 'banner2_subtitle',
                'group' => 'banners',
                'value_vi' => 'Trải nghiệm những hành trình khó quên cùng chúng tôi',
                'value_en' => 'Experience unforgettable journeys with us',
                'type' => 'string',
            ],
            [
                'key' => 'banner2_cta',
                'group' => 'banners',
                'value_vi' => 'Xem Tours',
                'value_en' => 'View Tours',
                'type' => 'string',
            ],
            [
                'key' => 'banner2_link',
                'group' => 'banners',
                'value_vi' => '/tours',
                'value_en' => '/tours',
                'type' => 'string',
            ],
            [
                'key' => 'banner2_image',
                'group' => 'banners',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],

            // About Page Settings
            [
                'key' => 'about_hero_title',
                'group' => 'about',
                'value_vi' => 'Về Chúng Tôi',
                'value_en' => 'About Us',
                'type' => 'string',
            ],
            [
                'key' => 'about_hero_subtitle',
                'group' => 'about',
                'value_vi' => 'Nơi nghỉ dưỡng lý tưởng giữa thiên nhiên',
                'value_en' => 'The perfect retreat in the heart of nature',
                'type' => 'string',
            ],
            [
                'key' => 'about_hero_image',
                'group' => 'about',
                'value_vi' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200',
                'value_en' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200',
                'type' => 'string',
            ],
            [
                'key' => 'about_story_title',
                'group' => 'about',
                'value_vi' => 'Câu chuyện của chúng tôi',
                'value_en' => 'Our Story',
                'type' => 'string',
            ],
            [
                'key' => 'about_story_content',
                'group' => 'about',
                'value_vi' => 'Happy Island Tour được thành lập với mong muốn mang đến cho du khách những trải nghiệm nghỉ dưỡng tuyệt vời nhất. Chúng tôi tin rằng mỗi chuyến đi là một cơ hội để khám phá, kết nối và tạo nên những kỷ niệm đáng nhớ.\n\nVới đội ngũ nhân viên tận tâm và hệ thống phòng nghỉ được thiết kế tinh tế, chúng tôi cam kết mang đến sự thoải mái và an yên cho mỗi vị khách.',
                'value_en' => 'Happy Island Tour was founded with the desire to provide guests with the best retreat experiences. We believe that every trip is an opportunity to explore, connect and create memorable moments.\n\nWith a dedicated team and thoughtfully designed rooms, we are committed to bringing comfort and peace to every guest.',
                'type' => 'string',
            ],
            [
                'key' => 'about_story_image',
                'group' => 'about',
                'value_vi' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
                'value_en' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
                'type' => 'string',
            ],
            [
                'key' => 'about_years_experience',
                'group' => 'about',
                'value_vi' => '10',
                'value_en' => '10',
                'type' => 'integer',
            ],
            [
                'key' => 'about_happy_guests',
                'group' => 'about',
                'value_vi' => '5000',
                'value_en' => '5000',
                'type' => 'integer',
            ],
            [
                'key' => 'about_rooms_tours',
                'group' => 'about',
                'value_vi' => '50',
                'value_en' => '50',
                'type' => 'integer',
            ],
            [
                'key' => 'about_rating',
                'group' => 'about',
                'value_vi' => '4.9',
                'value_en' => '4.9',
                'type' => 'float',
            ],

            // Hero Section Settings
            [
                'key' => 'hero_tagline',
                'group' => 'hero',
                'value_vi' => 'Retreat in effortless style',
                'value_en' => 'Retreat in effortless style',
                'type' => 'string',
            ],
            [
                'key' => 'hero_title',
                'group' => 'hero',
                'value_vi' => 'Chào mừng đến với Happy Island Tour của chúng tôi',
                'value_en' => 'Welcome to Our Happy Island Tour',
                'type' => 'string',
            ],
            [
                'key' => 'hero_subtitle',
                'group' => 'hero',
                'value_vi' => 'Trải nghiệm sự thoải mái và thiên nhiên hòa quyện hoàn hảo',
                'value_en' => 'Experience comfort and nature in perfect harmony',
                'type' => 'string',
            ],
            [
                'key' => 'hero_image_1',
                'group' => 'hero',
                'value_vi' => 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80',
                'value_en' => 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80',
                'type' => 'string',
            ],
            [
                'key' => 'hero_image_2',
                'group' => 'hero',
                'value_vi' => 'https://images.unsplash.com/photo-1439130490301-25e322d88054?auto=format&fit=crop&w=600&q=80',
                'value_en' => 'https://images.unsplash.com/photo-1439130490301-25e322d88054?auto=format&fit=crop&w=600&q=80',
                'type' => 'string',
            ],
            [
                'key' => 'hero_image_3',
                'group' => 'hero',
                'value_vi' => 'https://images.unsplash.com/photo-1505692794400-7fbb8246d57c?auto=format&fit=crop&w=500&q=80',
                'value_en' => 'https://images.unsplash.com/photo-1505692794400-7fbb8246d57c?auto=format&fit=crop&w=500&q=80',
                'type' => 'string',
            ],
            [
                'key' => 'hero_gallery_caption',
                'group' => 'hero',
                'value_vi' => 'Ẩn mình bên vịnh xanh',
                'value_en' => 'Hidden by the blue bay',
                'type' => 'string',
            ],
            [
                'key' => 'hero_floating_title',
                'group' => 'hero',
                'value_vi' => 'Trải nghiệm signature retreat',
                'value_en' => 'Experience signature retreat',
                'type' => 'string',
            ],
            [
                'key' => 'hero_floating_subtitle',
                'group' => 'hero',
                'value_vi' => '+320 khoảnh khắc được lưu giữ',
                'value_en' => '+320 moments captured',
                'type' => 'string',
            ],
            // Hero Stats
            [
                'key' => 'hero_stat1_value',
                'group' => 'hero',
                'value_vi' => '50+',
                'value_en' => '50+',
                'type' => 'string',
            ],
            [
                'key' => 'hero_stat1_label',
                'group' => 'hero',
                'value_vi' => 'Happy Island Tour được tuyển chọn',
                'value_en' => 'Happy Island Tours curated',
                'type' => 'string',
            ],
            [
                'key' => 'hero_stat2_value',
                'group' => 'hero',
                'value_vi' => '24',
                'value_en' => '24',
                'type' => 'string',
            ],
            [
                'key' => 'hero_stat2_label',
                'group' => 'hero',
                'value_vi' => 'Điểm đến',
                'value_en' => 'Destinations',
                'type' => 'string',
            ],
            [
                'key' => 'hero_stat3_value',
                'group' => 'hero',
                'value_vi' => '4.9/5',
                'value_en' => '4.9/5',
                'type' => 'string',
            ],
            [
                'key' => 'hero_stat3_label',
                'group' => 'hero',
                'value_vi' => 'Đánh giá khách',
                'value_en' => 'Guest reviews',
                'type' => 'string',
            ],
            [
                'key' => 'hero_stat4_value',
                'group' => 'hero',
                'value_vi' => '12+',
                'value_en' => '12+',
                'type' => 'string',
            ],
            [
                'key' => 'hero_stat4_label',
                'group' => 'hero',
                'value_vi' => 'Tours sẵn sàng',
                'value_en' => 'Tours ready',
                'type' => 'string',
            ],
            // Hero Perks
            [
                'key' => 'hero_perk1_icon',
                'group' => 'hero',
                'value_vi' => '🌿',
                'value_en' => '🌿',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk1_title',
                'group' => 'hero',
                'value_vi' => 'Eco-luxury stays',
                'value_en' => 'Eco-luxury stays',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk1_subtitle',
                'group' => 'hero',
                'value_vi' => 'Không gian xanh, tiện nghi cao cấp',
                'value_en' => 'Green spaces, premium amenities',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk2_icon',
                'group' => 'hero',
                'value_vi' => '🧭',
                'value_en' => '🧭',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk2_title',
                'group' => 'hero',
                'value_vi' => 'Local expert tours',
                'value_en' => 'Local expert tours',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk2_subtitle',
                'group' => 'hero',
                'value_vi' => 'Khám phá bản sắc địa phương',
                'value_en' => 'Discover local culture',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk3_icon',
                'group' => 'hero',
                'value_vi' => '💳',
                'value_en' => '💳',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk3_title',
                'group' => 'hero',
                'value_vi' => 'Secure payments',
                'value_en' => 'Secure payments',
                'type' => 'string',
            ],
            [
                'key' => 'hero_perk3_subtitle',
                'group' => 'hero',
                'value_vi' => 'SePay & PayPal được chứng nhận',
                'value_en' => 'Certified SePay & PayPal',
                'type' => 'string',
            ],
            // Trust section
            [
                'key' => 'hero_trust_title',
                'group' => 'hero',
                'value_vi' => '5k+ khách hài lòng',
                'value_en' => '5k+ happy guests',
                'type' => 'string',
            ],
            [
                'key' => 'hero_trust_subtitle',
                'group' => 'hero',
                'value_vi' => 'Được đánh giá 4.9/5 trên toàn cầu',
                'value_en' => 'Rated 4.9/5 worldwide',
                'type' => 'string',
            ],

            // Homepage Landing Settings
            [
                'key' => 'homepage_landing_enabled',
                'group' => 'homepage',
                'value_vi' => 'false',
                'value_en' => 'false',
                'type' => 'boolean',
            ],
            [
                'key' => 'homepage_banner_image',
                'group' => 'homepage',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'image',
            ],
            [
                'key' => 'homepage_wheel_image',
                'group' => 'homepage',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'image',
            ],
            [
                'key' => 'homepage_cloud_image_1',
                'group' => 'homepage',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'image',
            ],
            [
                'key' => 'homepage_cloud_image_2',
                'group' => 'homepage',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'image',
            ],
            [
                'key' => 'homepage_cloud_image_3',
                'group' => 'homepage',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'image',
            ],
            [
                'key' => 'homepage_cta_text',
                'group' => 'homepage',
                'value_vi' => 'Đặt ngay và tiết kiệm 10%',
                'value_en' => 'Book now & save 10%',
                'type' => 'string',
            ],
            [
                'key' => 'homepage_cta_sub',
                'group' => 'homepage',
                'value_vi' => 'Chỉ khả dụng trên Website',
                'value_en' => 'Only available on Website',
                'type' => 'string',
            ],
            [
                'key' => 'homepage_tagline',
                'group' => 'homepage',
                'value_vi' => 'Chỉ cần đặt chỗ trước - Không cần thẻ tín dụng - Thanh toán khi tham gia tour',
                'value_en' => 'Just reserve your spot - No credit card needed - Pay when you join the tour',
                'type' => 'string',
            ],
            [
                'key' => 'homepage_cta_link',
                'group' => 'homepage',
                'value_vi' => '/tours',
                'value_en' => '/tours',
                'type' => 'string',
            ],
            [
                'key' => 'homepage_signature_line1',
                'group' => 'homepage',
                'value_vi' => 'You Only',
                'value_en' => 'You Only',
                'type' => 'string',
            ],
            [
                'key' => 'homepage_signature_line2',
                'group' => 'homepage',
                'value_vi' => 'Live Once',
                'value_en' => 'Live Once',
                'type' => 'string',
            ],
            // Email Settings
            [
                'key' => 'mail_enable_notifications',
                'group' => 'email',
                'value_vi' => 'false',
                'value_en' => 'false',
                'type' => 'boolean',
            ],
            [
                'key' => 'mail_host',
                'group' => 'email',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],
            [
                'key' => 'mail_port',
                'group' => 'email',
                'value_vi' => '587',
                'value_en' => '587',
                'type' => 'integer',
            ],
            [
                'key' => 'mail_username',
                'group' => 'email',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],
            [
                'key' => 'mail_password',
                'group' => 'email',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],
            [
                'key' => 'mail_encryption',
                'group' => 'email',
                'value_vi' => 'tls',
                'value_en' => 'tls',
                'type' => 'string',
            ],
            [
                'key' => 'mail_from_address',
                'group' => 'email',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],
            [
                'key' => 'mail_from_name',
                'group' => 'email',
                'value_vi' => 'Happy Island Tour',
                'value_en' => 'Happy Island Tour',
                'type' => 'string',
            ],
            [
                'key' => 'mail_receive_address',
                'group' => 'email',
                'value_vi' => '',
                'value_en' => '',
                'type' => 'string',
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
